version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@17  
  pre_build:
    commands:
      - ng version
  build:
    commands:
      - ng build --configuration production
artifacts: 
  files:
    - 'dist/my-angular-project/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
  discard-paths: no
cache:
  paths:
    - node_modules/**/*  