version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
      - npm install  
  build:
    commands:
      - ng build --configuration production
      - find dist -type f | xargs ls -la
artifacts:
  base-directory: dist  
  files:
    - 'my-angular-project/**/*' 
    - appspec.yml
    - 'deploy-scripts/**/*'
  discard-paths: no